### ISSUE TITLE
;;) hangs the app

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/sgf#3]
I hope you don't mind all these issues, I'm making [my own SGF library in Go](https://github.com/fohristiwhirl/sgf) and so Sabaki is naturally something I'm using to test stuff.

Anyway, a file with (only) the bytes `;;)` hangs Sabaki. It is of course illegal, but should fail cleanly.

Edit: actually it seems `;;` is enough to hang it.

**Comment by yishn** [comment]
Not at all, keep these issues coming 😄. It seems we are too lenient/trusting with SGF input. `sgf` makes the (incorrect) assumption that nodes are always inside an opening parenthesis.

**Comment by fohristiwhirl** [comment]
On a semi-related issue, if a tree opens without a semi-colon, Sabaki interprets things in a way that is probably not what was intended.

`(B[pp];W[dd])`

Currently this gives 1 node, which is the white move. I think this should either fail entirely, or have 2 nodes.

**Comment by yishn** [comment]
That's what I mean by being lenient; if there's any way to parse an incorrect SGF, we will do it. And being able to parse it with the white move as the first node is still better than failing entirely. I've changed it so `sgf` will now also detect the black move as a node.
