### ISSUE TITLE
iconv and jscharder increase the size of the bundle by 500kb

### ISSUE THREAD

**Issue by proskurius** [SabakiHQ/sgf#4]
Hello.
I use the sgf-package in my project. And i was surprised when have seen the size of the bundle (generated by webpack).
I think, that its not ok.

**Comment by yishn** [comment]
iconv and jschardet are optional dependencies. You don‘t need to install them if you don’t want automatic encoding detection and decoding.

**Comment by proskurius** [comment]
Sorry, im beginner in programming. How can i dont install them? Remove functions from source code?

**Comment by yishn** [comment]
Normally, npm wouldn't install optional dependencies by default. You can uninstall them by running:

~~~
$ npm uninstall jschardet iconv-lite
~~~

You can also add the following to your webpack configuration:

~~~js
    externals: {
        'iconv-lite': 'null',
        'jschardet': 'null'
    }
~~~

**Comment by proskurius** [comment]
Ok. Thank you!

сб, 18 мая 2019 г., 16:17 Yichuan Shen <notifications@github.com>:
