### ISSUE TITLE
Sabaki not able to read SGF file but other programs can

### ISSUE THREAD

**Issue by aheavyburden** [SabakiHQ/sgf#5]
I'm running the latest version of Sabaki on my MacOS (Mojave). When I try to open the following SGF file in Sabaki I get the error "This file is unreadable".

However, when I try to open the file in another program such as Goban or even at http://goginkgo.github.io , it loads without any problems.

Any ideas? I'd like this to be fixed because at the moment, Sabaki is failing to read many SGFs that I have that work with other programs.

The following is the SGF file in question. Rename the extension to .sgf and try to open with Sabaki. After the file, I've added the raw contained text in the file containing the contents of the SGF file so you can look at it without downloading the attached .txt file.

**EDIT:** I've confirmed this SGF file can be opened in the web version of Sabaki: https://sabaki.yichuanshen.de/web/

[broken_sgf_in_sabaki.txt](https://github.com/SabakiHQ/Sabaki/files/3285429/broken_sgf_in_sabaki.txt)

<img width="600" alt="sgf file" src="https://user-images.githubusercontent.com/51782612/59422798-c95d1c00-8d85-11e9-900e-cf609a400043.png">

**Comment by yishn** [comment]
I would suggest you contact the developers running the No Name Go Server as well and tell them about this bug.

**Comment by aheavyburden** [comment]
They are aware that some SGFs don’t meet the standard protocol. I was just
hoping Sabaki could be made to load SGFs that aren’t perfect in formatting
just like the other Go clients that can read the corrupted files.
