### ISSUE TITLE
`ReferenceError: assignment to undeclared variable match` in tokenize

### ISSUE THREAD

**Issue by climu** [SabakiHQ/sgf#6]
I am starting to work on a goban widget using shudan, go-board and sgf [here](https://github.com/Awea/wshudan).

Calling `sgf.parse('(;B[aa]SZ[19];AB[cc][dd:ee])')` raise a javascript error `ReferenceError: assignment to undeclared variable match` related to `tokenise.js` file.

Changing this line:

https://github.com/SabakiHQ/sgf/blob/02de46af2307a003b8c038aa216b7ae3ea0a764a/src/tokenize.js#L21

to `var match = rules[type].exec(contents)`

Fix the issue.

**Comment by yishn** [comment]
Fixed in v3.4.2.

**Comment by climu** [comment]
Thanks!
