### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by MacErlang** [SabakiHQ/sgf#8]
Hello,

Just downloaded and installed the new version, and this problem has not been resolved.
In fact, the new version won't even properly display a file that has been explicitly declared to
be GB2312 encoded. Don't know what is going on? Please help!

I have attached two files, one is original, which won't display properly for either 4.4.3 or 5.0,
and the other has an added GB2312 declaration, which would then load properly for 4.3.3, but
NOT for 5.0.

Thanks,
Shun-Chen

[1020 Test.zip](https://github.com/SabakiHQ/sgf/files/4325245/1020.Test.zip)

_Originally posted by @MacErlang in https://github.com/SabakiHQ/sgf/issues/7#issuecomment-598278211_

**Comment by yishn** [comment]
Closing this as duplicate.
